### ISSUE TITLE
🐘の絵文字フォントを固定したい

### ISSUE THREAD

**Issue by lill-la** [katteni-kaihatu/zoubank-frontend#2]
# 概要
🐘に使われている絵文字フォントを指定して、どの環境でも同じ見た目になるようにしたい

# 目的
フォント指定が無いため口座ページの「🐘Bank」「🐘銀」「(残高)🐘」などの見た目が環境によって異なっている。
文字はいいが、絵文字は大きく見た目が異なるためブランドイメージがブレるのはよろしくないと思われるので統一したい。

# 追加情報
- misskey.resonite.loveでよく使われている🐘は[twemoji](https://github.com/twitter/twemoji)のもの

**Comment by lill-la** [comment]
twitter版twemojiは更新停止こちらがOSSの後継版っぽい
https://github.com/jdecked/twemoji

**Comment by rassi0429** [comment]
[v0.1.6](https://github.com/katteni-kaihatu/zoubank-frontend/releases/tag/v0.1.6)
